// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkMMR4EfZeshXKcQGK4BMdMdSu8FCzkAA',
    appId: '1:95768080470:web:85342cdd9974485754cbf7',
    messagingSenderId: '95768080470',
    projectId: 'noting-it',
    authDomain: 'noting-it.firebaseapp.com',
    storageBucket: 'noting-it.appspot.com',
    measurementId: 'G-7D7LGG380H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeWfLlB8leyG6GJ7tKzvKj2wna-3je3P4',
    appId: '1:95768080470:android:56e306ecfc177d5854cbf7',
    messagingSenderId: '95768080470',
    projectId: 'noting-it',
    storageBucket: 'noting-it.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH2O8Xl4bbnO5Iu-J5UCgB54hq40tHqRQ',
    appId: '1:95768080470:ios:1d5479a37a9118b554cbf7',
    messagingSenderId: '95768080470',
    projectId: 'noting-it',
    storageBucket: 'noting-it.appspot.com',
    iosBundleId: 'com.example.notingit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH2O8Xl4bbnO5Iu-J5UCgB54hq40tHqRQ',
    appId: '1:95768080470:ios:1d5479a37a9118b554cbf7',
    messagingSenderId: '95768080470',
    projectId: 'noting-it',
    storageBucket: 'noting-it.appspot.com',
    iosBundleId: 'com.example.notingit',
  );
}
